// packages/solid/src/context.ts
import type { KeelSeed, PageContext } from "@kolektiv/keel"
import { createContext, useContext, type Accessor } from "solid-js"

/**
 * Value provided by the page mount to layouts and the page component. The
 * signals are stable for the lifetime of the page module, so `update(ctx)`
 * propagates by writing them instead of remounting the tree.
 */
export interface KeelProviderValue<T = unknown> {
  seed: Accessor<KeelSeed<T> | undefined>
  context: Accessor<PageContext<T> | undefined>
}

/** @internal Used by `createPage`; prefer `usePageContext()` in app code. */
export const KEEL_CONTEXT = createContext<KeelProviderValue>()

/**
 * The `PageContext` accessor for the mounted page: route params, payload,
 * validation errors, theme, shared values, and `navigate`. This is the Solid
 * equivalent of the `ctx` prop Svelte pages and layouts receive. The accessor
 * is reactive: `createPage` writes the shared context signal on `update(ctx)`,
 * so descendants see context changes without remounting.
 */
export function usePageContext<T = unknown>(): Accessor<PageContext<T>> {
  const value = useContext(KEEL_CONTEXT)
  if (!value) throw new Error("Keel: usePageContext() must be called inside a pack page")
  return value.context as Accessor<PageContext<T>>
}

// packages/angular/src/context.ts
import { InjectionToken, inject, signal, type Signal, type WritableSignal } from "@angular/core"
import type { PageContext } from "@kolektiv/keel"

/**
 * Reactive holder for the `PageContext` of the mounted page. `createPage()`
 * provides one instance per mount through the mount's environment injector,
 * and `update(ctx)` replaces the value without re-creating the component
 * tree, so every descendant that reads {@link KeelContext.context} sees the
 * new route params, payload, and errors from the next change detection pass.
 */
export class KeelContext<T = unknown> {
  private readonly state: WritableSignal<PageContext<T>>

  /** The current context as a signal; read it in templates and computeds. */
  readonly context: Signal<PageContext<T>>

  constructor(initial: PageContext<T>) {
    this.state = signal(initial)
    this.context = this.state.asReadonly()
  }

  set(value: PageContext<T>): void {
    this.state.set(value)
  }
}

/**
 * Token for the active mount's {@link KeelContext}. `createPage()` provides
 * it in the per-mount environment injector; there is exactly one holder per
 * mounted page tree.
 */
export const KEEL_CONTEXT = new InjectionToken<KeelContext>("keel.context")

/**
 * The `PageContext` for the mounted page as a signal: route params, payload,
 * validation errors, theme, shared values, and `navigate`. This is the
 * Angular equivalent of the `ctx` prop Svelte pages and layouts receive.
 *
 * ```ts
 * export default class Page {
 *   readonly ctx = injectKeelContext<HomePage>()
 * }
 * ```
 */
export function injectKeelContext<T = unknown>(): Signal<PageContext<T>> {
  const holder = inject(KEEL_CONTEXT, { optional: true })
  if (!holder) {
    throw new Error("Keel: injectKeelContext() is only available inside a page mounted by createPage()")
  }
  return holder.context as Signal<PageContext<T>>
}
