// packages/lit/src/page.ts
import {
  getPage,
  getProcessing,
  subscribe,
  subscribeProcessing,
  type KeelSeed,
} from "@kolektiv/keel"
import type { ReactiveController, ReactiveControllerHost } from "lit"

/** Seed plus router state, shaped like Svelte's `page()` proxy. */
export type KeelPage<T = unknown> = KeelSeed<T> & { processing: boolean }

/**
 * Reactive read of the core seed store for one host. Subscribes on connect and
 * caches the last `{ ...seed, processing }` snapshot, so repeated reads
 * between store changes return the same object and only a visit, reload, or
 * processing change requests an update — exactly one snapshot identity per
 * change, like the other adapters' `usePage`.
 */
export class KeelPageController<T = unknown> implements ReactiveController {
  #seed: KeelSeed<T> | undefined
  #processing = false
  #snapshot: KeelPage<T> | undefined
  #unsubscribe: (() => void) | undefined
  #unsubscribeProcessing: (() => void) | undefined

  constructor(private readonly host: ReactiveControllerHost) {
    host.addController(this)
  }

  hostConnected(): void {
    this.#unsubscribe = subscribe(() => this.#refresh())
    this.#unsubscribeProcessing = subscribeProcessing(() => this.#refresh())
  }

  hostDisconnected(): void {
    this.#unsubscribe?.()
    this.#unsubscribe = undefined
    this.#unsubscribeProcessing?.()
    this.#unsubscribeProcessing = undefined
  }

  /** The cached snapshot; reads the store directly before the first update. */
  get current(): KeelPage<T> {
    if (!this.#snapshot) this.#refresh()
    return this.#snapshot!
  }

  #refresh(): void {
    const seed = getPage<T>()
    const processing = getProcessing() > 0
    if (seed === this.#seed && processing === this.#processing) return
    this.#seed = seed
    this.#processing = processing
    this.#snapshot = { ...seed, processing }
    this.host.requestUpdate()
  }
}

/** Controller factory: `readonly page = usePage(this)` in a `KeelElement`. */
export function usePage<T = unknown>(host: ReactiveControllerHost): KeelPageController<T> {
  return new KeelPageController<T>(host)
}

// packages/angular/src/page.ts
import { DestroyRef, inject, signal, type Signal } from "@angular/core"
import {
  getPage,
  getProcessing,
  subscribe,
  subscribeProcessing,
  type KeelSeed,
} from "@kolektiv/keel"

/** Seed plus router state, shaped like Svelte's `page()` proxy. */
export type KeelPage<T = unknown> = KeelSeed<T> & { processing: boolean }

/**
 * The current seed store snapshot as a signal, including the router
 * `processing` flag. One store subscription per injecting component or
 * service, disposed with the injection context; the snapshot object identity
 * only changes when a visit, reload, or processing change actually applies.
 *
 * ```ts
 * export default class Page {
 *   readonly page = injectKeelPage<HomePage>()
 * }
 * ```
 */
export function injectKeelPage<T = unknown>(): Signal<KeelPage<T>> {
  const destroyRef = inject(DestroyRef)
  const state = signal<KeelPage<T>>({ ...getPage<T>(), processing: getProcessing() > 0 })
  let seed: KeelSeed<T> = getPage<T>()
  let processing = getProcessing() > 0

  const refresh = (): void => {
    const nextSeed = getPage<T>()
    const nextProcessing = getProcessing() > 0
    if (nextSeed === seed && nextProcessing === processing) return
    seed = nextSeed
    processing = nextProcessing
    state.set({ ...nextSeed, processing: nextProcessing })
  }

  const unsubscribe = subscribe(refresh)
  const unsubscribeProcessing = subscribeProcessing(refresh)
  destroyRef.onDestroy(() => {
    unsubscribe()
    unsubscribeProcessing()
  })
  return state.asReadonly()
}
