// packages/vue/src/Form.vue
<script lang="ts">
import type { Method, VisitOptions } from "@kolektiv/keel"

export interface FormProps {
  action: string
  method?: Method
  resetOnSuccess?: boolean
  replace?: boolean
  preserveScroll?: VisitOptions["preserveScroll"]
  preserveState?: boolean
  headers?: Record<string, string>
  force?: boolean
  onBefore?: VisitOptions["onBefore"]
  onSuccess?: VisitOptions["onSuccess"]
  onError?: VisitOptions["onError"]
  onSubmit?: (event: SubmitEvent) => void
}
</script>

<script setup lang="ts">
import { router } from "@kolektiv/keel"

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<FormProps>(), {
  method: "post",
  resetOnSuccess: false,
  replace: false,
  preserveScroll: false,
  preserveState: true,
  force: false,
})

function handleSubmit(event: SubmitEvent) {
  props.onSubmit?.(event)
  if (event.defaultPrevented) return
  event.preventDefault()
  const form = event.currentTarget as HTMLFormElement
  void router.visit(props.action, {
    method: props.method,
    data: new FormData(form),
    preserveScroll: props.preserveScroll,
    preserveState: props.preserveState,
    replace: props.replace,
    headers: props.headers,
    force: props.force,
    onBefore: props.onBefore,
    onError: props.onError,
    onSuccess(page) {
      if (props.resetOnSuccess) form.reset()
      props.onSuccess?.(page)
    },
  })
}
</script>

<template>
  <form :action="action" :method="method" v-bind="$attrs" @submit="handleSubmit">
    <slot />
  </form>
</template>

// packages/react/src/Form.tsx
import { router, type Method, type VisitOptions } from "@kolektiv/keel"
import {
  type FormEvent,
  type FormHTMLAttributes,
  type ReactNode,
} from "react"

export interface FormProps
  extends Omit<FormHTMLAttributes<HTMLFormElement>, "action" | "method" | "onError" | "onSubmit">,
    Pick<
      VisitOptions,
      | "replace"
      | "preserveScroll"
      | "preserveState"
      | "headers"
      | "force"
      | "onBefore"
      | "onSuccess"
      | "onError"
    > {
  action: string
  method?: Method
  resetOnSuccess?: boolean
  onSubmit?: (event: FormEvent<HTMLFormElement>) => void
  children?: ReactNode
}

/**
 * Form submission through `router.visit`. Serializes the form to `FormData`;
 * `onSuccess` resets the fields when `resetOnSuccess` is set.
 */
export function Form({
  action,
  method = "post",
  preserveScroll = false,
  preserveState = true,
  replace = false,
  resetOnSuccess = false,
  headers,
  force = false,
  onBefore,
  onSuccess,
  onError,
  onSubmit,
  children,
  ...rest
}: FormProps) {
  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    onSubmit?.(event)
    if (event.defaultPrevented) return
    event.preventDefault()
    const form = event.currentTarget
    void router.visit(action, {
      method,
      data: new FormData(form),
      preserveScroll,
      preserveState,
      replace,
      headers,
      force,
      onBefore,
      onError,
      onSuccess(page) {
        if (resetOnSuccess) form.reset()
        onSuccess?.(page)
      },
    })
  }

  return (
    <form action={action} method={method} onSubmit={handleSubmit} {...rest}>
      {children}
    </form>
  )
}
