// packages/angular/src/guards.ts
import { DestroyRef, inject } from "@angular/core"
import { router, type NavigationGuard } from "@kolektiv/keel"

/**
 * Registers a navigation guard for the lifetime of the calling component,
 * service, or directive. Registration happens at injection time and the
 * dispose function runs from `DestroyRef.onDestroy`.
 */
export function injectNavigationGuard(guard: NavigationGuard): void {
  const destroyRef = inject(DestroyRef)
  destroyRef.onDestroy(router.beforeEach(guard))
}

/**
 * Native `beforeunload` prompt while `isDirty()` returns true. The listener
 * is attached at injection time and removed from `DestroyRef.onDestroy`.
 */
export function injectUnloadGuard(isDirty: () => boolean): void {
  const destroyRef = inject(DestroyRef)
  if (typeof window === "undefined") return
  const listener = (event: BeforeUnloadEvent): void => {
    if (!isDirty()) return
    event.preventDefault()
    event.returnValue = ""
  }
  window.addEventListener("beforeunload", listener)
  destroyRef.onDestroy(() => window.removeEventListener("beforeunload", listener))
}

// packages/react/src/guards.ts
import { router, type NavigationGuard } from "@kolektiv/keel"
import { useEffect } from "react"

/**
 * Registers a navigation guard for the lifetime of the calling component.
 * Re-registers when `guard` changes; unregisters on unmount.
 */
export function useNavigationGuard(guard: NavigationGuard): void {
  useEffect(() => router.beforeEach(guard), [guard])
}

/**
 * Native `beforeunload` prompt while `isDirty()` returns true. The listener
 * is attached on mount and removed on unmount.
 */
export function useUnloadGuard(isDirty: () => boolean): void {
  useEffect(() => {
    if (typeof window === "undefined") return
    const listener = (event: BeforeUnloadEvent) => {
      if (!isDirty()) return
      event.preventDefault()
      event.returnValue = ""
    }
    window.addEventListener("beforeunload", listener)
    return () => window.removeEventListener("beforeunload", listener)
  }, [isDirty])
}
