// packages/solid/src/mount.tsx
import {
  applyHead,
  fromPageHead,
  getPage,
  type KeelSeed,
  type PageContext,
  type PageModule,
} from "@kolektiv/keel"
import { createEffect, createSignal, onCleanup, type Component, type JSX } from "solid-js"
import { render } from "solid-js/web"
import { KEEL_CONTEXT, type KeelProviderValue } from "./context.js"
import { usePage } from "./page.js"

/** Layout component: wraps `children`, outermost layout first. */
type KeelLayout = Component<{ children?: JSX.Element }>

function markMountError(target: Element, error: unknown): void {
  if (target.querySelector("[data-keel-mount-error]")) return
  const pre = target.ownerDocument.createElement("pre")
  pre.setAttribute("data-keel-mount-error", "")
  pre.textContent = error instanceof Error ? error.stack ?? error.message : String(error)
  target.append(pre)
}

/** Applied once by the root, never by nested layouts or pages. */
function PageHead(): JSX.Element {
  const seed = usePage()
  createEffect(() => {
    const head = seed().head
    if (!head) return
    onCleanup(applyHead(fromPageHead(head)))
  })
  return null
}

function Nest(props: { layouts: KeelLayout[]; Page: Component; index: number }): JSX.Element {
  const Layout = props.layouts[props.index]
  if (!Layout) {
    const Page = props.Page
    return <Page />
  }
  return (
    <Layout>
      <Nest layouts={props.layouts} Page={props.Page} index={props.index + 1} />
    </Layout>
  )
}

/**
 * Mount factory for pack entries. Renders into the host with `render()` from
 * `solid-js/web` — never hydration — because the document shell is
 * Kotlin-authored HTML, not Solid markup. Layouts nest outermost-first; the
 * seed head is applied once at the root; `update(ctx)` writes the shared seed
 * and context signals, so descendants re-render in place with the new context
 * without remounting. Solid commits synchronously, so the DOM is up to date
 * when `mount` / `update` return. Mount errors are marked on the host with
 * `<pre data-keel-mount-error>` and rethrown.
 */
export function createPage<T = unknown>(
  Page: Component,
  layouts: KeelLayout[] = [],
): PageModule<T> {
  const [seed, setSeed] = createSignal<KeelSeed<T>>()
  const [context, setContext] = createSignal<PageContext<T>>()
  const provider: KeelProviderValue = { seed, context }
  let dispose: (() => void) | undefined

  function Root(): JSX.Element {
    return (
      <KEEL_CONTEXT.Provider value={provider}>
        <PageHead />
        <Nest layouts={layouts} Page={Page} index={0} />
      </KEEL_CONTEXT.Provider>
    )
  }

  return {
    mount(nextHost, nextContext) {
      dispose?.()
      dispose = undefined
      nextHost.replaceChildren()
      setSeed(() => getPage<T>())
      setContext(() => nextContext)
      try {
        dispose = render(() => <Root />, nextHost)
      } catch (error) {
        markMountError(nextHost, error)
        throw error
      }
    },
    unmount() {
      if (!dispose) return
      const current = dispose
      dispose = undefined
      current()
    },
    update(nextContext) {
      if (!dispose) return
      setSeed(() => getPage<T>())
      setContext(() => nextContext)
    },
  }
}

// packages/preact/src/mount.tsx
import {
  applyHead,
  fromPageHead,
  type PageContext,
  type PageModule,
} from "@kolektiv/keel"
import { Component, createElement, render, type ComponentChildren, type ComponentType } from "preact"
import { useLayoutEffect } from "preact/hooks"
import { KeelProvider } from "./context.js"
import { usePage } from "./page.js"

/** Layout component: wraps `children`, outermost layout first. */
type KeelLayout = ComponentType<{ children?: ComponentChildren }>

function markMountError(target: Element, error: unknown): void {
  if (target.querySelector("[data-keel-mount-error]")) return
  const pre = target.ownerDocument.createElement("pre")
  pre.setAttribute("data-keel-mount-error", "")
  pre.textContent = error instanceof Error ? error.stack ?? error.message : String(error)
  target.append(pre)
}

interface MountErrorBoundaryProps {
  host: Element
  children?: ComponentChildren
}

/**
 * Preact error boundaries call `componentDidCatch`; rethrowing there keeps the
 * error unhandled, so Preact walks on to outer boundaries and finally throws it
 * out of `render()` — the marker stays on the host for the mount contract.
 */
class MountErrorBoundary extends Component<MountErrorBoundaryProps> {
  componentDidCatch(error: unknown): void {
    markMountError(this.props.host, error)
    throw error
  }

  render(): ComponentChildren {
    return this.props.children
  }
}

function Nest({
  layouts,
  Page,
  index,
}: {
  layouts: KeelLayout[]
  Page: ComponentType
  index: number
}): ComponentChildren {
  if (index >= layouts.length) return createElement(Page, null)
  const Layout = layouts[index]
  return createElement(Layout, null, createElement(Nest, { layouts, Page, index: index + 1 }))
}

/** Applied once by the root, never by nested layouts or pages. */
function PageHead(): null {
  const seed = usePage()
  useLayoutEffect(() => {
    if (!seed.head) return
    return applyHead(fromPageHead(seed.head))
  }, [seed.head])
  return null
}

function Root({
  layouts,
  Page,
  ctx,
}: {
  layouts: KeelLayout[]
  Page: ComponentType
  ctx: PageContext
}) {
  const seed = usePage()
  return (
    <KeelProvider seed={seed} context={ctx}>
      <PageHead />
      <Nest layouts={layouts} Page={Page} index={0} />
    </KeelProvider>
  )
}

/**
 * Mount factory for pack entries. Renders into the host with `render()` from
 * `preact` — never hydration — because the document shell is Kotlin-authored
 * HTML, not Preact markup. Layouts nest outermost-first; the seed head is
 * applied once at the root; `update(ctx)` re-renders with the new context so
 * descendants see it without remounting; `unmount()` calls `render(null, …)`
 * to tear the tree down. Preact commits synchronously, so the DOM is up to
 * date when `mount` / `update` return. Mount errors are marked on the host
 * with `<pre data-keel-mount-error>` and rethrown.
 */
export function createPage<T = unknown>(
  Page: ComponentType,
  layouts: KeelLayout[] = [],
): PageModule<T> {
  let host: Element | undefined
  let ctx: PageContext<T> | undefined

  function renderTree(): void {
    if (!host || !ctx) return
    render(
      <MountErrorBoundary host={host}>
        <Root layouts={layouts} Page={Page} ctx={ctx} />
      </MountErrorBoundary>,
      host,
    )
  }

  return {
    mount(nextHost, nextContext) {
      if (host) render(null, host)
      nextHost.replaceChildren()
      host = nextHost
      ctx = nextContext
      try {
        renderTree()
      } catch (error) {
        markMountError(nextHost, error)
        throw error
      }
    },
    unmount() {
      if (!host) return
      const current = host
      host = undefined
      ctx = undefined
      render(null, current)
    },
    update(nextContext) {
      if (!host) return
      ctx = nextContext
      renderTree()
    },
  }
}
